// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a target of an invocation over HTTP.
public struct Destination: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Network config is used to configure how Eventarc resolves and
  /// connect to a destination.
  /// This should only be used with HttpEndpoint destination type.
  public var networkConfig: NetworkConfig? = nil

  public var descriptor: OneOf_Descriptor? = nil

  /// Initialize a new instance of `Destination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Destination().with { $0.cloudRun = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudRun = "cloudRun"
    case cloudFunction = "cloudFunction"
    case gke = "gke"
    case workflow = "workflow"
    case httpEndpoint = "httpEndpoint"
    case networkConfig = "networkConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.networkConfig = try container.decodeIfPresent(NetworkConfig.self, forKey: .networkConfig)

    var descriptor: OneOf_Descriptor? = nil
    let descriptorCheckAndSet = {
      if descriptor != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'descriptor'"))
      }
      descriptor = $0
    }
    if let cloudRun = try container.decodeIfPresent(CloudRun?.self, forKey: .cloudRun) {
      try descriptorCheckAndSet(.cloudRun(cloudRun))
    }
    if let cloudFunction = try container.decodeIfPresent(Swift.String.self, forKey: .cloudFunction)
    {
      try descriptorCheckAndSet(.cloudFunction(cloudFunction))
    }
    if let gke = try container.decodeIfPresent(GKE?.self, forKey: .gke) {
      try descriptorCheckAndSet(.gke(gke))
    }
    if let workflow = try container.decodeIfPresent(Swift.String.self, forKey: .workflow) {
      try descriptorCheckAndSet(.workflow(workflow))
    }
    if let httpEndpoint = try container.decodeIfPresent(HttpEndpoint?.self, forKey: .httpEndpoint) {
      try descriptorCheckAndSet(.httpEndpoint(httpEndpoint))
    }
    self.descriptor = descriptor
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.networkConfig, forKey: .networkConfig)

    if let choice = self.descriptor {
      switch choice {
      case .cloudRun(let value):
        try container.encode(value, forKey: .cloudRun)
      case .cloudFunction(let value):
        try container.encode(value, forKey: .cloudFunction)
      case .gke(let value):
        try container.encode(value, forKey: .gke)
      case .workflow(let value):
        try container.encode(value, forKey: .workflow)
      case .httpEndpoint(let value):
        try container.encode(value, forKey: .httpEndpoint)
      }
    }
  }

  public enum OneOf_Descriptor: Codable, Equatable, Sendable {
    /// Cloud Run fully-managed resource that receives the events. The resource
    /// should be in the same project as the trigger.
    indirect case cloudRun(CloudRun?)
    /// The Cloud Function resource name. Cloud Functions V1 and V2 are
    /// supported.
    /// Format: `projects/{project}/locations/{location}/functions/{function}`
    ///
    /// This is a read-only field. Creating Cloud Functions V1/V2 triggers is
    /// only supported via the Cloud Functions product. An error will be returned
    /// if the user sets this value.
    case cloudFunction(Swift.String)
    /// A GKE service capable of receiving events. The service should be running
    /// in the same project as the trigger.
    indirect case gke(GKE?)
    /// The resource name of the Workflow whose Executions are triggered by
    /// the events. The Workflow resource should be deployed in the same project
    /// as the trigger.
    /// Format: `projects/{project}/locations/{location}/workflows/{workflow}`
    case workflow(Swift.String)
    /// An HTTP endpoint destination described by an URI.
    indirect case httpEndpoint(HttpEndpoint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.Destination"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
