// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An enrollment represents a subscription for messages on a particular message
/// bus. It defines a matching criteria for messages on the bus and the
/// subscriber endpoint where matched messages should be delivered.
public struct Enrollment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the form
  /// projects/{project}/locations/{location}/enrollments/{enrollment}
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the channel. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and might be sent only on update and delete requests to
  /// ensure that the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Resource labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Resource annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Resource display name.
  public var displayName: Swift.String = Swift.String()

  /// Required. A CEL expression identifying which messages this enrollment
  /// applies to.
  public var celMatch: Swift.String = Swift.String()

  /// Required. Immutable. Resource name of the message bus identifying the
  /// source of the messages. It matches the form
  /// projects/{project}/locations/{location}/messageBuses/{messageBus}.
  public var messageBus: Swift.String = Swift.String()

  /// Required. Destination is the Pipeline that the Enrollment is delivering to.
  /// It must point to the full resource name of a Pipeline. Format:
  /// "projects/{PROJECT_ID}/locations/{region}/pipelines/{PIPELINE_ID)"
  public var destination: Swift.String = Swift.String()

  /// Initialize a new instance of `Enrollment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Enrollment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.Enrollment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
