// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class EventarcTransport: EventarcStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://eventarc.googleapis.com",
      )
    }

    public func getTrigger(
      request: GetTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Trigger {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.Trigger.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listTriggers(
      request: ListTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListTriggersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/triggers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListTriggersResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createTrigger(
      request: CreateTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/triggers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.triggerId, prefix: "triggerId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.trigger {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateTrigger(
      request: UpdateTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.trigger.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trigger.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.trigger {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteTrigger(
      request: DeleteTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getChannel(
      request: GetChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Channel {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.Channel.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listChannels(
      request: ListChannelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/channels"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListChannelsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createChannel(
      request: CreateChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/channels"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.channelId, prefix: "channelId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.channel {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateChannel(
      request: UpdateChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.channel.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.channel.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.channel {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteChannel(
      request: DeleteChannelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getProvider(
      request: GetProviderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Provider {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.Provider.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listProviders(
      request: ListProvidersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListProvidersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/providers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListProvidersResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getChannelConnection(
      request: GetChannelConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ChannelConnection {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ChannelConnection.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listChannelConnections(
      request: ListChannelConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelConnectionsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/channelConnections"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListChannelConnectionsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createChannelConnection(
      request: CreateChannelConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/channelConnections"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.channelConnectionId, prefix: "channelConnectionId"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.channelConnection {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteChannelConnection(
      request: DeleteChannelConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getGoogleChannelConfig(
      request: GetGoogleChannelConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.GoogleChannelConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateGoogleChannelConfig(
      request: UpdateGoogleChannelConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.googleChannelConfig.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.google_channel_config.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.googleChannelConfig {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudEventarcV1.GoogleChannelConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getMessageBus(
      request: GetMessageBusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.MessageBus {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.MessageBus.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listMessageBuses(
      request: ListMessageBusesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/messageBuses"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListMessageBusesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listMessageBusEnrollments(
      request: ListMessageBusEnrollmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusEnrollmentsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0):listEnrollments"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListMessageBusEnrollmentsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createMessageBus(
      request: CreateMessageBusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/messageBuses"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.messageBusId, prefix: "messageBusId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.messageBus {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateMessageBus(
      request: UpdateMessageBusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.messageBus.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.message_bus.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.messageBus {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteMessageBus(
      request: DeleteMessageBusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getEnrollment(
      request: GetEnrollmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Enrollment {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.Enrollment.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listEnrollments(
      request: ListEnrollmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListEnrollmentsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/enrollments"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListEnrollmentsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createEnrollment(
      request: CreateEnrollmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/enrollments"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.enrollmentId, prefix: "enrollmentId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.enrollment {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateEnrollment(
      request: UpdateEnrollmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.enrollment.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.enrollment.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.enrollment {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteEnrollment(
      request: DeleteEnrollmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getPipeline(
      request: GetPipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Pipeline {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.Pipeline.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPipelines(
      request: ListPipelinesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListPipelinesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/pipelines"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListPipelinesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createPipeline(
      request: CreatePipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/pipelines"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pipelineId, prefix: "pipelineId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.pipeline {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updatePipeline(
      request: UpdatePipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.pipeline.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.pipeline.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.pipeline {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deletePipeline(
      request: DeletePipelineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getGoogleApiSource(
      request: GetGoogleApiSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleApiSource {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.GoogleApiSource.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listGoogleApiSources(
      request: ListGoogleApiSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListGoogleApiSourcesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/googleApiSources"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudEventarcV1.ListGoogleApiSourcesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createGoogleApiSource(
      request: CreateGoogleApiSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/googleApiSources"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.googleApiSourceId, prefix: "googleApiSourceId"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.googleApiSource {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateGoogleApiSource(
      request: UpdateGoogleApiSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.googleApiSource.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.google_api_source.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.googleApiSource {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteGoogleApiSource(
      request: DeleteGoogleApiSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
      query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/locations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):setIamPolicy"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleIAMV1.Policy.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):getIamPolicy"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.options, prefix: "options"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleIAMV1.Policy.self, timeout: options.attemptTimeout
      ).get()
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):testIamPermissions"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleIAMV1.TestIamPermissionsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/operations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.returnPartialSuccess, prefix: "returnPartialSuccess")
      )
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):cancel"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
