// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A representation of the event type resource.
public struct EventType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The full name of the event type (for example,
  /// "google.cloud.storage.object.v1.finalized"). In the form of
  /// {provider-specific-prefix}.{resource}.{version}.{verb}. Types MUST be
  /// versioned and event schemas are guaranteed to remain backward compatible
  /// within one version. Note that event type versions and API versions do not
  /// need to match.
  public var type: Swift.String = Swift.String()

  /// Output only. Human friendly description of what the event type is about.
  /// For example "Bucket created in Cloud Storage".
  public var description: Swift.String = Swift.String()

  /// Output only. Filtering attributes for the event type.
  public var filteringAttributes: [FilteringAttribute] = []

  /// Output only. URI for the event schema.
  /// For example
  /// "https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/storage/v1/events.proto"
  public var eventSchemaUri: Swift.String = Swift.String()

  /// Initialize a new instance of `EventType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventType().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.EventType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
