// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol EventarcStub: Sendable {
    func getTrigger(
      request: GetTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Trigger

    func listTriggers(
      request: ListTriggersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListTriggersResponse

    func createTrigger(
      request: CreateTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateTrigger(
      request: UpdateTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTrigger(
      request: DeleteTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getChannel(
      request: GetChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Channel

    func listChannels(
      request: ListChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelsResponse

    func createChannel(
      request: CreateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateChannel(
      request: UpdateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteChannel(
      request: DeleteChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getProvider(
      request: GetProviderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Provider

    func listProviders(
      request: ListProvidersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListProvidersResponse

    func getChannelConnection(
      request: GetChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ChannelConnection

    func listChannelConnections(
      request: ListChannelConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelConnectionsResponse

    func createChannelConnection(
      request: CreateChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteChannelConnection(
      request: DeleteChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getGoogleChannelConfig(
      request: GetGoogleChannelConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig

    func updateGoogleChannelConfig(
      request: UpdateGoogleChannelConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig

    func getMessageBus(
      request: GetMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.MessageBus

    func listMessageBuses(
      request: ListMessageBusesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusesResponse

    func listMessageBusEnrollments(
      request: ListMessageBusEnrollmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusEnrollmentsResponse

    func createMessageBus(
      request: CreateMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMessageBus(
      request: UpdateMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMessageBus(
      request: DeleteMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getEnrollment(
      request: GetEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Enrollment

    func listEnrollments(
      request: ListEnrollmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListEnrollmentsResponse

    func createEnrollment(
      request: CreateEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEnrollment(
      request: UpdateEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEnrollment(
      request: DeleteEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPipeline(
      request: GetPipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Pipeline

    func listPipelines(
      request: ListPipelinesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListPipelinesResponse

    func createPipeline(
      request: CreatePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePipeline(
      request: UpdatePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePipeline(
      request: DeletePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getGoogleApiSource(
      request: GetGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleApiSource

    func listGoogleApiSources(
      request: ListGoogleApiSourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListGoogleApiSourcesResponse

    func createGoogleApiSource(
      request: CreateGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateGoogleApiSource(
      request: UpdateGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteGoogleApiSource(
      request: DeleteGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
