// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class EventarcLogging: EventarcStub {
    let inner: any EventarcStub
    let logger: Logger

    public init(_ inner: any EventarcStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-eventarc-v1"
      logger[metadataKey: "gcp.client.service"] = "eventarc"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Eventarc"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getTrigger(
      request: GetTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Trigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTrigger",
        action: {
          (r: GetTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.Trigger
          in
          return try await self.inner.getTrigger(request: r, options: o)
        })
    }

    public func listTriggers(
      request: ListTriggersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListTriggersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTriggers",
        action: {
          (r: ListTriggersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListTriggersResponse
          in
          return try await self.inner.listTriggers(request: r, options: o)
        })
    }

    public func createTrigger(
      request: CreateTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTrigger",
        action: {
          (r: CreateTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTrigger(request: r, options: o)
        })
    }

    public func updateTrigger(
      request: UpdateTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTrigger",
        action: {
          (r: UpdateTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTrigger(request: r, options: o)
        })
    }

    public func deleteTrigger(
      request: DeleteTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTrigger",
        action: {
          (r: DeleteTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTrigger(request: r, options: o)
        })
    }

    public func getChannel(
      request: GetChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Channel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getChannel",
        action: {
          (r: GetChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.Channel
          in
          return try await self.inner.getChannel(request: r, options: o)
        })
    }

    public func listChannels(
      request: ListChannelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listChannels",
        action: {
          (r: ListChannelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListChannelsResponse
          in
          return try await self.inner.listChannels(request: r, options: o)
        })
    }

    public func createChannel(
      request: CreateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChannel",
        action: {
          (r: CreateChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createChannel(request: r, options: o)
        })
    }

    public func updateChannel(
      request: UpdateChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateChannel",
        action: {
          (r: UpdateChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateChannel(request: r, options: o)
        })
    }

    public func deleteChannel(
      request: DeleteChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteChannel",
        action: {
          (r: DeleteChannelRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteChannel(request: r, options: o)
        })
    }

    public func getProvider(
      request: GetProviderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Provider {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProvider",
        action: {
          (r: GetProviderRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.Provider
          in
          return try await self.inner.getProvider(request: r, options: o)
        })
    }

    public func listProviders(
      request: ListProvidersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListProvidersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProviders",
        action: {
          (r: ListProvidersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListProvidersResponse
          in
          return try await self.inner.listProviders(request: r, options: o)
        })
    }

    public func getChannelConnection(
      request: GetChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ChannelConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getChannelConnection",
        action: {
          (r: GetChannelConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ChannelConnection
          in
          return try await self.inner.getChannelConnection(request: r, options: o)
        })
    }

    public func listChannelConnections(
      request: ListChannelConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListChannelConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listChannelConnections",
        action: {
          (r: ListChannelConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListChannelConnectionsResponse
          in
          return try await self.inner.listChannelConnections(request: r, options: o)
        })
    }

    public func createChannelConnection(
      request: CreateChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChannelConnection",
        action: {
          (r: CreateChannelConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createChannelConnection(request: r, options: o)
        })
    }

    public func deleteChannelConnection(
      request: DeleteChannelConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteChannelConnection",
        action: {
          (r: DeleteChannelConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteChannelConnection(request: r, options: o)
        })
    }

    public func getGoogleChannelConfig(
      request: GetGoogleChannelConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGoogleChannelConfig",
        action: {
          (r: GetGoogleChannelConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.GoogleChannelConfig
          in
          return try await self.inner.getGoogleChannelConfig(request: r, options: o)
        })
    }

    public func updateGoogleChannelConfig(
      request: UpdateGoogleChannelConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleChannelConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGoogleChannelConfig",
        action: {
          (r: UpdateGoogleChannelConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.GoogleChannelConfig
          in
          return try await self.inner.updateGoogleChannelConfig(request: r, options: o)
        })
    }

    public func getMessageBus(
      request: GetMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.MessageBus {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMessageBus",
        action: {
          (r: GetMessageBusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.MessageBus
          in
          return try await self.inner.getMessageBus(request: r, options: o)
        })
    }

    public func listMessageBuses(
      request: ListMessageBusesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMessageBuses",
        action: {
          (r: ListMessageBusesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListMessageBusesResponse
          in
          return try await self.inner.listMessageBuses(request: r, options: o)
        })
    }

    public func listMessageBusEnrollments(
      request: ListMessageBusEnrollmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListMessageBusEnrollmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMessageBusEnrollments",
        action: {
          (r: ListMessageBusEnrollmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListMessageBusEnrollmentsResponse
          in
          return try await self.inner.listMessageBusEnrollments(request: r, options: o)
        })
    }

    public func createMessageBus(
      request: CreateMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMessageBus",
        action: {
          (r: CreateMessageBusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMessageBus(request: r, options: o)
        })
    }

    public func updateMessageBus(
      request: UpdateMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateMessageBus",
        action: {
          (r: UpdateMessageBusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMessageBus(request: r, options: o)
        })
    }

    public func deleteMessageBus(
      request: DeleteMessageBusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMessageBus",
        action: {
          (r: DeleteMessageBusRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMessageBus(request: r, options: o)
        })
    }

    public func getEnrollment(
      request: GetEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Enrollment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEnrollment",
        action: {
          (r: GetEnrollmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.Enrollment
          in
          return try await self.inner.getEnrollment(request: r, options: o)
        })
    }

    public func listEnrollments(
      request: ListEnrollmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListEnrollmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEnrollments",
        action: {
          (r: ListEnrollmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListEnrollmentsResponse
          in
          return try await self.inner.listEnrollments(request: r, options: o)
        })
    }

    public func createEnrollment(
      request: CreateEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEnrollment",
        action: {
          (r: CreateEnrollmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEnrollment(request: r, options: o)
        })
    }

    public func updateEnrollment(
      request: UpdateEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEnrollment",
        action: {
          (r: UpdateEnrollmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateEnrollment(request: r, options: o)
        })
    }

    public func deleteEnrollment(
      request: DeleteEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEnrollment",
        action: {
          (r: DeleteEnrollmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEnrollment(request: r, options: o)
        })
    }

    public func getPipeline(
      request: GetPipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.Pipeline {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPipeline",
        action: {
          (r: GetPipelineRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.Pipeline
          in
          return try await self.inner.getPipeline(request: r, options: o)
        })
    }

    public func listPipelines(
      request: ListPipelinesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListPipelinesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPipelines",
        action: {
          (r: ListPipelinesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListPipelinesResponse
          in
          return try await self.inner.listPipelines(request: r, options: o)
        })
    }

    public func createPipeline(
      request: CreatePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPipeline",
        action: {
          (r: CreatePipelineRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPipeline(request: r, options: o)
        })
    }

    public func updatePipeline(
      request: UpdatePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePipeline",
        action: {
          (r: UpdatePipelineRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePipeline(request: r, options: o)
        })
    }

    public func deletePipeline(
      request: DeletePipelineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePipeline",
        action: {
          (r: DeletePipelineRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePipeline(request: r, options: o)
        })
    }

    public func getGoogleApiSource(
      request: GetGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.GoogleApiSource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGoogleApiSource",
        action: {
          (r: GetGoogleApiSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.GoogleApiSource
          in
          return try await self.inner.getGoogleApiSource(request: r, options: o)
        })
    }

    public func listGoogleApiSources(
      request: ListGoogleApiSourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEventarcV1.ListGoogleApiSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGoogleApiSources",
        action: {
          (r: ListGoogleApiSourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEventarcV1.ListGoogleApiSourcesResponse
          in
          return try await self.inner.listGoogleApiSources(request: r, options: o)
        })
    }

    public func createGoogleApiSource(
      request: CreateGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGoogleApiSource",
        action: {
          (r: CreateGoogleApiSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGoogleApiSource(request: r, options: o)
        })
    }

    public func updateGoogleApiSource(
      request: UpdateGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateGoogleApiSource",
        action: {
          (r: UpdateGoogleApiSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGoogleApiSource(request: r, options: o)
        })
    }

    public func deleteGoogleApiSource(
      request: DeleteGoogleApiSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGoogleApiSource",
        action: {
          (r: DeleteGoogleApiSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGoogleApiSource(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
