// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A representation of the FilteringAttribute resource.
/// Filtering attributes are per event type.
public struct FilteringAttribute: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Attribute used for filtering the event type.
  public var attribute: Swift.String = Swift.String()

  /// Output only. Description of the purpose of the attribute.
  public var description: Swift.String = Swift.String()

  /// Output only. If true, the triggers for this provider should always specify
  /// a filter on these attributes. Trigger creation will fail otherwise.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Output only. If true, the attribute accepts matching expressions in the
  /// Eventarc PathPattern format.
  public var pathPatternSupported: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `FilteringAttribute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FilteringAttribute().with { $0.attribute = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case attribute = "attribute"
    case description = "description"
    case `required` = "required"
    case pathPatternSupported = "pathPatternSupported"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.attribute = try container.decode(Swift.String.self, forKey: .attribute)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.`required` = try container.decode(Swift.Bool.self, forKey: .`required`)
    self.pathPatternSupported = try container.decode(Swift.Bool.self, forKey: .pathPatternSupported)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.attribute, forKey: .attribute)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encode(self.pathPatternSupported, forKey: .pathPatternSupported)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.FilteringAttribute"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
