// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a GKE destination.
public struct GKE: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the cluster the GKE service is running in. The
  /// cluster must be running in the same project as the trigger being created.
  public var cluster: Swift.String = Swift.String()

  /// Required. The name of the Google Compute Engine in which the cluster
  /// resides, which can either be compute zone (for example, us-central1-a) for
  /// the zonal clusters or region (for example, us-central1) for regional
  /// clusters.
  public var location: Swift.String = Swift.String()

  /// Required. The namespace the GKE service is running in.
  public var namespace: Swift.String = Swift.String()

  /// Required. Name of the GKE service.
  public var service: Swift.String = Swift.String()

  /// Optional. The relative path on the GKE service the events should be sent
  /// to.
  ///
  /// The value must conform to the definition of a URI path segment (section 3.3
  /// of RFC2396). Examples: "/route", "route", "route/subroute".
  public var path: Swift.String = Swift.String()

  /// Initialize a new instance of `GKE`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GKE().with { $0.cluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.GKE"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
