// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A GoogleApiSource represents a subscription of 1P events from a MessageBus.
public struct GoogleApiSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the form
  /// projects/{project}/locations/{location}/googleApiSources/{google_api_source}
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the channel. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and might be sent only on update and delete requests to
  /// ensure that the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Resource labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Resource annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Resource display name.
  public var displayName: Swift.String = Swift.String()

  /// Required. Destination is the message bus that the GoogleApiSource is
  /// delivering to. It must be point to the full resource name of a MessageBus.
  /// Format:
  /// "projects/{PROJECT_ID}/locations/{region}/messagesBuses/{MESSAGE_BUS_ID)
  public var destination: Swift.String = Swift.String()

  /// Optional. Resource name of a KMS crypto key (managed by the user) used to
  /// encrypt/decrypt their event data.
  ///
  /// It must match the pattern
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  public var cryptoKeyName: Swift.String = Swift.String()

  /// Optional. Config to control Platform logging for the GoogleApiSource.
  public var loggingConfig: LoggingConfig? = nil

  /// Config to enabled subscribing to events from other projects in the org.
  ///
  /// Users need the eventarc.googleApiSource.create permission on the entire org
  /// in order to create a resource with these settings.
  public var wideScopeSubscription: OneOf_WideScopeSubscription? = nil

  /// Initialize a new instance of `GoogleApiSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoogleApiSource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case uid = "uid"
    case etag = "etag"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case annotations = "annotations"
    case displayName = "displayName"
    case destination = "destination"
    case cryptoKeyName = "cryptoKeyName"
    case loggingConfig = "loggingConfig"
    case organizationSubscription = "organizationSubscription"
    case projectSubscriptions = "projectSubscriptions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.uid = try container.decode(Swift.String.self, forKey: .uid)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.destination = try container.decode(Swift.String.self, forKey: .destination)
    self.cryptoKeyName = try container.decode(Swift.String.self, forKey: .cryptoKeyName)
    self.loggingConfig = try container.decodeIfPresent(LoggingConfig.self, forKey: .loggingConfig)

    var wideScopeSubscription: OneOf_WideScopeSubscription? = nil
    let wideScopeSubscriptionCheckAndSet = {
      if wideScopeSubscription != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'wideScopeSubscription'"))
      }
      wideScopeSubscription = $0
    }
    if let organizationSubscription = try container.decodeIfPresent(
      GoogleApiSource.OrganizationSubscription?.self, forKey: .organizationSubscription)
    {
      try wideScopeSubscriptionCheckAndSet(.organizationSubscription(organizationSubscription))
    }
    if let projectSubscriptions = try container.decodeIfPresent(
      GoogleApiSource.ProjectSubscriptions?.self, forKey: .projectSubscriptions)
    {
      try wideScopeSubscriptionCheckAndSet(.projectSubscriptions(projectSubscriptions))
    }
    self.wideScopeSubscription = wideScopeSubscription
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.destination, forKey: .destination)
    try container.encode(self.cryptoKeyName, forKey: .cryptoKeyName)
    try container.encode(self.loggingConfig, forKey: .loggingConfig)

    if let choice = self.wideScopeSubscription {
      switch choice {
      case .organizationSubscription(let value):
        try container.encode(value, forKey: .organizationSubscription)
      case .projectSubscriptions(let value):
        try container.encode(value, forKey: .projectSubscriptions)
      }
    }
  }

  /// Config to enable subscribing to all events from a list of projects.
  public struct ProjectSubscriptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. A list of projects to receive events from.
    ///
    /// All the projects must be in the same org. The listed projects should have
    /// the format project/{identifier} where identifier can be either the
    /// project id for project number. A single list may contain both formats. At
    /// most 100 projects can be listed.
    public var list: [Swift.String] = []

    /// Initialize a new instance of `ProjectSubscriptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProjectSubscriptions().with { $0.list = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.v1.GoogleApiSource.ProjectSubscriptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Config to enabled subscribing to events from other projects in the org.
  public struct OrganizationSubscription: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Enable org level subscription.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `OrganizationSubscription`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OrganizationSubscription().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.v1.GoogleApiSource.OrganizationSubscription"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Config to enabled subscribing to events from other projects in the org.
  ///
  /// Users need the eventarc.googleApiSource.create permission on the entire org
  /// in order to create a resource with these settings.
  public enum OneOf_WideScopeSubscription: Codable, Equatable, Sendable {
    /// Optional. Config to enable subscribing to events from all projects in the
    /// GoogleApiSource's org.
    indirect case organizationSubscription(GoogleApiSource.OrganizationSubscription?)
    /// Optional. Config to enable subscribing to all events from a list of
    /// projects.
    ///
    /// All the projects must be in the same org as the GoogleApiSource.
    indirect case projectSubscriptions(GoogleApiSource.ProjectSubscriptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.GoogleApiSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
