// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a HTTP endpoint destination.
public struct HttpEndpoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The URI of the HTTP endpoint.
  ///
  /// The value must be a RFC2396 URI string.
  /// Examples: `http://10.10.10.8:80/route`,
  /// `http://svc.us-central1.p.local:8080/`.
  /// Only HTTP and HTTPS protocols are supported. The host can be either a
  /// static IP addressable from the VPC specified by the network config, or
  /// an internal DNS hostname of the service resolvable via Cloud DNS.
  public var uri: Swift.String = Swift.String()

  /// Initialize a new instance of `HttpEndpoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpEndpoint().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.HttpEndpoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
