// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the transport intermediaries created for the trigger to
/// deliver events.
public struct Transport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var intermediary: OneOf_Intermediary? = nil

  /// Initialize a new instance of `Transport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Transport().with { $0.pubsub = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case pubsub = "pubsub"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var intermediary: OneOf_Intermediary? = nil
    let intermediaryCheckAndSet = {
      if intermediary != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'intermediary'"))
      }
      intermediary = $0
    }
    if let pubsub = try container.decodeIfPresent(Pubsub?.self, forKey: .pubsub) {
      try intermediaryCheckAndSet(.pubsub(pubsub))
    }
    self.intermediary = intermediary
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.intermediary {
      switch choice {
      case .pubsub(let value):
        try container.encode(value, forKey: .pubsub)
      }
    }
  }

  public enum OneOf_Intermediary: Codable, Equatable, Sendable {
    /// The Pub/Sub topic and subscription used by Eventarc as a transport
    /// intermediary.
    indirect case pubsub(Pubsub?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.Transport"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
