// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A representation of the trigger resource.
public struct Trigger: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the trigger. Must be unique within the
  /// location of the project and must be in
  /// `projects/{project}/locations/{location}/triggers/{trigger}` format.
  public var name: Swift.String = Swift.String()

  /// Output only. Server-assigned unique identifier for the trigger. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. Unordered list. The list of filters that applies to event
  /// attributes. Only events that match all the provided filters are sent to the
  /// destination.
  public var eventFilters: [EventFilter] = []

  /// Optional. The IAM service account email associated with the trigger. The
  /// service account represents the identity of the trigger.
  ///
  /// The `iam.serviceAccounts.actAs` permission must be granted on the service
  /// account to allow a principal to impersonate the service account. For more
  /// information, see the
  /// [Roles and permissions](/eventarc/docs/all-roles-permissions) page specific
  /// to the trigger destination.
  public var serviceAccount: Swift.String = Swift.String()

  /// Required. Destination specifies where the events should be sent to.
  public var destination: Destination? = nil

  /// Optional. To deliver messages, Eventarc might use other Google Cloud
  /// products as a transport intermediary. This field contains a reference to
  /// that transport intermediary. This information can be used for debugging
  /// purposes.
  public var transport: Transport? = nil

  /// Optional. User labels attached to the triggers that can be used to group
  /// resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The name of the channel associated with the trigger in
  /// `projects/{project}/locations/{location}/channels/{channel}` format.
  /// You must provide a channel to receive events from Eventarc SaaS partners.
  public var channel: Swift.String = Swift.String()

  /// Output only. The reason(s) why a trigger is in FAILED state.
  public var conditions: [Swift.String: StateCondition] = [:]

  /// Optional. EventDataContentType specifies the type of payload in MIME
  /// format that is expected from the CloudEvent data field. This is set to
  /// `application/json` if the value is not defined.
  public var eventDataContentType: Swift.String = Swift.String()

  /// Output only. Whether or not this Trigger satisfies the requirements of
  /// physical zone separation
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Optional. The retry policy to use in the Trigger.
  ///
  /// If unset, event delivery will be retried for up to 24 hours by default:
  /// https://cloud.google.com/eventarc/docs/retry-events
  public var retryPolicy: Trigger.RetryPolicy? = nil

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and might be sent only on create requests to ensure that the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Trigger`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Trigger().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The retry policy configuration for the Trigger.
  ///
  /// Can only be set with Cloud Run destinations.
  public struct RetryPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The maximum number of delivery attempts for any message. The
    /// only valid value is 1.
    public var maxAttempts: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `RetryPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RetryPolicy().with { $0.maxAttempts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.v1.Trigger.RetryPolicy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.Trigger"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
