// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the UpdateChannel method.
public struct UpdateChannelRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The channel to be updated.
  public var channel: Channel? = nil

  /// The fields to be updated; only fields explicitly provided are updated.
  /// If no field mask is provided, all provided fields in the request are
  /// updated. To update all fields, provide a field mask of "*".
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If set, validate the request and preview the review, but do not
  /// post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateChannelRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateChannelRequest().with { $0.channel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.UpdateChannelRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
